# Generated by Django 4.2 on 2023-04-27 12:11

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('ratings', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('star_rating', models.FloatField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('photo', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500)),
                ('ratings', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('star_rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
        ),
    ]
