# Generated by Django 4.2 on 2023-04-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
