# Generated by Django 4.2 on 2023-04-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviewer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ratings',
        ),
    ]
