# Generated by Django 4.2 on 2023-04-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='reviews.comment'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='reviews.reviewer'),
        ),
    ]
