# Generated by Django 4.1.7 on 2023-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_comment_star_rating_rating_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='type',
        ),
        migrations.AddField(
            model_name='review',
            name='overview',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_data',
            field=models.IntegerField(default=2023),
        ),
    ]
