# Generated by Django 4.1.7 on 2023-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_type_review_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
