# Generated by Django 4.1.7 on 2023-04-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
    ]
