# Generated by Django 4.1.7 on 2023-04-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_remove_rating_comment_rating_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='avg_rating',
        ),
    ]
