# Generated by Django 4.1.7 on 2023-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_reviewer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='photo',
            field=models.CharField(default='/static/reviews/media/default.png', max_length=250),
        ),
    ]
